service: transl-service-sls
frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-central-1
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action: ["translate:TranslateText"]
          Resource: "*"
        - Effect: Allow
          Action: ["comprehend:DetectDominantLanguage"]
          Resource: "*"

functions:
  handler:
    handler: handler.handler
    events:
      - httpApi: "POST /translate"
